const C=[
['주택 매매 자금계획','집값·현금·대출로 추가 필요 현금을 확인합니다.','#2f80ed',[['price','집값','50000'],['cash','보유 현금','7000'],['loan','대출금','35000'],['cost','취득·부대비용','1500']],v=>`추가 필요 현금: <b>${won(Math.max(0,v.price-v.cash-v.loan+v.cost))}</b>`],
['취득세','주택 가격과 취득세율로 단순 취득세를 계산합니다.','#ef4f76',[['price','주택 가격','50000'],['rate','취득세율(%)','1']],v=>`예상 취득세: <b>${won(v.price*v.rate/100)}</b>`],
['전세자금','보증금·대출금·금리로 자기자금과 월 이자를 계산합니다.','#36ad83',[['deposit','전세보증금','30000'],['loan','전세대출','24000'],['rate','연 금리(%)','3.5']],v=>`필요 자기자금: <b>${won(v.deposit-v.loan)}</b><br>월 이자: <b>${won(v.loan*v.rate/100/12)}</b>`],
['LTV','주택가격과 LTV 비율로 대출 가능 금액을 계산합니다.','#ff851b',[['price','주택 가격','50000'],['ltv','LTV(%)','70']],v=>`LTV 기준 한도: <b>${won(v.price*v.ltv/100)}</b>`],
['DTI','연소득 대비 연간 부채상환액 비율을 계산합니다.','#7656c9',[['income','연소득','3600'],['annual','연간 주택대출 원리금','900'],['other','기타 연간 부채상환액','100']],v=>`예상 DTI: <b>${pct((v.annual+v.other)/v.income*100)}</b>`],
['DSR','연소득 대비 모든 대출의 연간 원리금 비율을 계산합니다.','#31a77b',[['income','연소득','3600'],['annual','연간 총 원리금','900']],v=>`예상 DSR: <b>${pct(v.annual/v.income*100)}</b>`],
['중개보수','거래금액과 중개보수율로 예상 중개보수를 계산합니다.','#3287e8',[['amount','거래금액','50000'],['rate','중개보수율(%)','0.4']],v=>`예상 중개보수: <b>${won(v.amount*v.rate/100)}</b>`],
['재산세','과세표준과 세율로 단순 재산세를 계산합니다.','#31a77b',[['base','과세표준','20000'],['rate','재산세율(%)','0.1']],v=>`예상 재산세: <b>${won(v.base*v.rate/100)}</b>`],
['청약 자금계획','분양가와 계약금·중도금·잔금 비율을 계산합니다.','#ff851b',[['price','분양가','50000'],['contract','계약금(%)','10'],['middle','중도금(%)','60'],['balance','잔금(%)','30']],v=>`계약금 <b>${won(v.price*v.contract/100)}</b> / 중도금 <b>${won(v.price*v.middle/100)}</b> / 잔금 <b>${won(v.price*v.balance/100)}</b>`],
['월 상환금','대출금·금리·기간으로 원리금균등 월 상환액을 계산합니다.','#7656c9',[['loan','대출금','30000'],['rate','연 금리(%)','4'],['years','대출기간(년)','30']],v=>{let P=v.loan*10000,r=v.rate/1200,n=v.years*12,m=r?P*r*(1+r)**n/((1+r)**n-1):P/n;return`월 상환액: <b>${won(m/10000)}</b><br>총 상환액: <b>${won(m*n/10000)}</b>`})];
const grid=document.querySelector('#grid');C.forEach((c,i)=>grid.innerHTML+=`<article class="card" style="--a:${c[2]}"><div class="num">${String(i+1).padStart(2,'0')}</div><h3>${c[0]}</h3><p>${c[1]}</p><button class="btn" onclick="openCalc(${i})">계산하기 →</button></article>`);let cur=0;const won=n=>`${Math.round(n).toLocaleString('ko-KR')}만원`,pct=n=>`${n.toFixed(1)}%`;function openCalc(i){cur=i;let c=C[i];document.querySelector('#title').textContent=c[0];document.querySelector('#form').innerHTML=c[3].map(f=>`<div class="field"><label>${f[1]}</label><input id="f_${f[0]}" type="number" value="${f[2]}" inputmode="decimal"></div>`).join('')+'<button class="calc" onclick="calc()">계산하기</button>';document.querySelector('#result').textContent='값을 입력하고 계산해 주세요.';document.querySelector('#modal').style.display='grid'}function calc(){let v={};C[cur][3].forEach(f=>v[f[0]]=Number(document.querySelector('#f_'+f[0]).value||0));document.querySelector('#result').innerHTML=C[cur][4](v)}function closeCalc(){document.querySelector('#modal').style.display='none'}
