const C=[
{t:'주택 매매 자금계획',f:[['price','집값','50000'],['cash','보유 현금','7000'],['loan','대출금','35000'],['cost','취득·부대비용','1500']],r:v=>`추가 필요 현금: <b>${won(Math.max(0,v.price-v.cash-v.loan+v.cost))}</b>`},
{t:'취득세',f:[['price','주택 가격','50000'],['rate','취득세율(%)','1']],r:v=>`예상 취득세: <b>${won(v.price*v.rate/100)}</b>`},
{t:'전세자금',f:[['deposit','전세보증금','30000'],['loan','전세대출','24000'],['rate','연 금리(%)','3.5']],r:v=>`필요 자기자금: <b>${won(v.deposit-v.loan)}</b><br>월 이자: <b>${won(v.loan*v.rate/100/12)}</b>`},
{t:'LTV',f:[['price','주택 가격','50000'],['ltv','LTV(%)','70']],r:v=>`LTV 기준 대출한도: <b>${won(v.price*v.ltv/100)}</b>`},
{t:'DTI',f:[['income','연소득','3600'],['annual','연간 주택대출 원리금','900'],['other','기타 연간 부채상환액','100']],r:v=>`예상 DTI: <b>${pct((v.annual+v.other)/v.income*100)}</b>`},
{t:'DSR',f:[['income','연소득','3600'],['annual','연간 총 원리금','900']],r:v=>`예상 DSR: <b>${pct(v.annual/v.income*100)}</b>`},
{t:'중개보수',f:[['amount','거래금액','50000'],['rate','중개보수율(%)','0.4']],r:v=>`예상 중개보수: <b>${won(v.amount*v.rate/100)}</b>`},
{t:'재산세',f:[['base','과세표준','20000'],['rate','재산세율(%)','0.1']],r:v=>`예상 재산세: <b>${won(v.base*v.rate/100)}</b>`},
{t:'청약 자금계획',f:[['price','분양가','50000'],['contract','계약금(%)','10'],['middle','중도금(%)','60'],['balance','잔금(%)','30']],r:v=>`계약금 <b>${won(v.price*v.contract/100)}</b><br>중도금 <b>${won(v.price*v.middle/100)}</b><br>잔금 <b>${won(v.price*v.balance/100)}</b>`},
{t:'월 상환금',f:[['loan','대출금','30000'],['rate','연 금리(%)','4'],['years','대출기간(년)','30']],r:v=>{const P=v.loan*10000,r=v.rate/1200,n=v.years*12,m=r?P*r*(1+r)**n/((1+r)**n-1):P/n;return`월 상환액: <b>${won(m/10000)}</b><br>총 상환액: <b>${won(m*n/10000)}</b>`}}
];let cur=0;const won=n=>`${Math.round(n).toLocaleString('ko-KR')}만원`,pct=n=>`${n.toFixed(1)}%`;function openCalc(i){cur=i;const c=C[i];document.querySelector('#title').textContent=c.t;document.querySelector('#form').innerHTML=c.f.map(x=>`<div class="field"><label>${x[1]}</label><input id="f_${x[0]}" type="number" value="${x[2]}" inputmode="decimal"></div>`).join('')+'<button class="calc" onclick="calculate()">계산하기</button>';document.querySelector('#result').textContent='값을 입력하고 계산해 주세요.';document.querySelector('#modal').style.display='grid'}function calculate(){const v={};C[cur].f.forEach(x=>v[x[0]]=Number(document.querySelector('#f_'+x[0]).value||0));document.querySelector('#result').innerHTML=C[cur].r(v)}function closeCalc(){document.querySelector('#modal').style.display='none'}